name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Cordova
        run: npm install -g cordova@10

      - name: Add Android Platform
        run: cordova platform add android

      - name: Build Debug APK
        run: cordova build android --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-vida-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
