name: Build Cordova Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install dependencies and platforms
        run: |
          npm install
          cordova platform add android

      - name: Build APK
        run: cordova build android --release
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
        name: mi-vida-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
